Fix the composer provide rule
slimphp/Slim-Http pull request #138
Opened 2020-10-22 10:47 UTC by stof

This package does not provide the code of the psr/http-factory package (which defines interfaces). It provides psr/http-factory-implementation which is the virtual package to represent implementations of the interface.
Providing the wrong package while also requiring it creates issues with Composer 2, because the solver will consider that install psr/http-factory is not necessary as it is already provided.

Refs https://github.com/composer/composer/issues/9316

2020-10-22 10:56 UTC, Seldaek approved these changes

2020-10-24 19:39 UTC, proton-ab commented
Any news here? This is blocking composer update.

2020-10-25 18:33 UTC, t0mmy742 requested changes

2020-10-25 18:33 UTC, t0mmy742 commented on composer.json
> +    "psr/http-factory-implementation": "1.0"
As mentioned by @proton-ab, this package is set of decorators. It needs real implementations to work. Please edit your PR to remove all packages from the `provide` section.

2020-10-26 08:17 UTC, l-x commented
With the release of composer v2 this issue got serious. Composer now removes psr/http-factory when installing slm/http.

2020-10-26 09:19 UTC, stof commented on composer.json
> +    "psr/http-factory-implementation": "1.0"
done

2020-10-26 09:29 UTC, t0mmy742 approved these changes

2020-10-26 10:38 UTC, proton-ab approved these changes

2020-10-29 01:40 UTC, l0gicgate approved these changes

2020-10-29 01:40 UTC, merged

2020-10-29 16:44 UTC, proton-ab commented
Needs release of new version

2020-10-29 17:01 UTC, l0gicgate commented
@proton-ab here you go https://github.com/slimphp/Slim-Http/releases/tag/1.1.0